BEGIN;

-- Seed tags
INSERT INTO tags (name, created_at) VALUES
  ('ios', NOW()),
  ('android', NOW()),
  ('web', NOW()),
  ('backend', NOW()),
  ('viking', NOW()),
  ('odin', NOW()),
  ('payments', NOW()),
  ('autocomplete', NOW()),
  ('onboarding', NOW()),
  ('performance', NOW());

-- Seed tickets
INSERT INTO tickets (title, description, status, created_at, updated_at) VALUES
  ('Implement autocomplete in global search', 'Add autocomplete suggestions to the main search bar on the web dashboard.', 'open', NOW(), NOW()),
  ('Fix iOS login button overlap', 'On iOS devices with small screens, the login button overlaps the keyboard.', 'open', NOW(), NOW()),
  ('Android dark mode polish', 'Audit Android dark mode styles and fix unreadable text on the settings screen.', 'open', NOW(), NOW()),
  ('Viking project: payment webhook handler', 'Implement webhook handler for Stripe payment events in the Viking project backend.', 'open', NOW(), NOW()),
  ('Optimize onboarding funnel analytics', 'Track each onboarding step to understand where users drop off.', 'open', NOW(), NOW()),
  ('Autocomplete for tag input', 'When typing tags for a ticket, show autocomplete for existing tags.', 'open', NOW(), NOW()),
  ('Payments retry mechanism', 'Add automatic retry for failed payment charges with exponential backoff.', 'open', NOW(), NOW()),
  ('iOS push notification badge count', 'Badge count is not updated when new tickets are assigned on iOS.', 'open', NOW(), NOW()),
  ('Android push notification channel setup', 'Create high-priority notification channel for critical ticket updates.', 'done', NOW(), NOW()),
  ('Web dashboard performance audit', 'Run Lighthouse on the ticket list page and document performance issues.', 'open', NOW(), NOW()),
  ('Backend cleanup of legacy ticket status', 'Remove deprecated ticket status values and migrate to open/done.', 'done', NOW(), NOW()),
  ('Implement infinite scroll on ticket list', 'Replace pagination with infinite scroll for a smoother UX.', 'open', NOW(), NOW()),
  ('Add saved filters for web ticket list', 'Allow users to save frequently used ticket filter combinations.', 'open', NOW(), NOW()),
  ('Android offline ticket creation', 'Allow tickets to be created offline and synced when connection returns.', 'open', NOW(), NOW()),
  ('iOS keyboard accessory actions', 'Add quick actions (Next, Done) to the keyboard accessory for forms.', 'open', NOW(), NOW()),
  ('Viking project: feature flag service', 'Introduce a simple feature flag service for Viking experiments.', 'open', NOW(), NOW()),
  ('Payments reconciliation script', 'Daily job to reconcile payment provider records with internal tickets.', 'open', NOW(), NOW()),
  ('Refactor ticket search backend query', 'Simplify SQL for ticket search and add proper indexes.', 'open', NOW(), NOW()),
  ('Improve onboarding empty state copy', 'Rewrite onboarding empty states to better guide new users.', 'done', NOW(), NOW()),
  ('Add loading skeletons to ticket list', 'Show skeleton loading state instead of spinners on web.', 'open', NOW(), NOW()),
  ('Autocomplete suggestions ranking', 'Rank autocomplete suggestions by recent usage and relevance.', 'open', NOW(), NOW()),
  ('Viking project: deployment checklist', 'Create a deployment checklist document for Viking releases.', 'done', NOW(), NOW()),
  ('Backend health check endpoint', 'Add /health endpoint reporting DB connectivity and version.', 'done', NOW(), NOW()),
  ('Android crash on ticket detail', 'Fix crash when opening ticket detail with missing description.', 'open', NOW(), NOW()),
  ('iOS share ticket as PDF', 'Allow sharing ticket details as a generated PDF from the app.', 'open', NOW(), NOW()),
  ('Web: keyboard shortcuts for ticket actions', 'Add shortcuts for complete, edit, and delete actions.', 'open', NOW(), NOW()),
  ('Performance profiling for large ticket lists', 'Profile backend and frontend when loading 10k tickets.', 'open', NOW(), NOW()),
  ('Add bulk complete action', 'Allow marking multiple tickets as done from the list.', 'open', NOW(), NOW()),
  ('Onboarding checklist for new admins', 'Create an onboarding checklist section specifically for admins.', 'open', NOW(), NOW()),
  ('Payments test environment data reset', 'Automate resetting payments test data every night.', 'done', NOW(), NOW()),
  ('Autocomplete keyboard navigation', 'Support arrow keys and Enter for selecting autocomplete options.', 'open', NOW(), NOW()),
  ('Viking project: iOS build pipeline', 'Set up CI pipeline to build and sign the Viking iOS app.', 'open', NOW(), NOW()),
  ('Android build pipeline caching', 'Enable Gradle caching to speed up Android CI builds.', 'open', NOW(), NOW()),
  ('Backend rate limiting for public APIs', 'Protect public ticket APIs with simple rate limiting.', 'open', NOW(), NOW()),
  ('Web responsive layout for ticket board', 'Make ticket board work well on tablets and small laptops.', 'open', NOW(), NOW()),
  ('Improve performance of tag filter queries', 'Optimize SQL for filtering tickets by multiple tags (AND logic).', 'open', NOW(), NOW()),
  ('Onboarding email sequence review', 'Review copy and timing of onboarding emails for new users.', 'done', NOW(), NOW()),
  ('Payments failure notification to admins', 'Notify admins in Slack when payment failures spike.', 'open', NOW(), NOW()),
  ('Autocomplete caching strategy', 'Cache frequent autocomplete results on the client to reduce API calls.', 'open', NOW(), NOW()),
  ('iOS accessibility audit', 'Run VoiceOver accessibility checks on the iOS ticket screens.', 'open', NOW(), NOW()),
  ('Android accessibility labels', 'Ensure all Android ticket action buttons have content descriptions.', 'open', NOW(), NOW()),
  ('Backend logging standardization', 'Standardize log format and log levels for ticket operations.', 'open', NOW(), NOW()),
  ('Web: ticket detail side panel', 'Open ticket details in a side panel instead of a full page.', 'open', NOW(), NOW()),
  ('Viking project: beta feedback form', 'Embed a feedback form inside the Viking app for beta users.', 'open', NOW(), NOW()),
  ('Onboarding progress indicator', 'Show a progress bar for users going through onboarding steps.', 'open', NOW(), NOW()),
  ('Performance budget for homepage', 'Define and document performance budgets for the main pages.', 'open', NOW(), NOW()),
  ('Payments refund flow UX', 'Design and implement a clear refund flow in the UI.', 'open', NOW(), NOW()),
  ('Autocomplete language support', 'Ensure autocomplete works well with CJK and right-to-left languages.', 'open', NOW(), NOW()),
  ('Backend data export for tickets', 'Provide CSV export of tickets filtered by tag and status.', 'open', NOW(), NOW()),
  ('Web: global search bar placement', 'Reposition the global search bar to be more discoverable.', 'open', NOW(), NOW());

-- Seed ticket-tag relationships
-- Assumes tags have IDs 1..10 in the same order as inserted above
-- and tickets have IDs 1..50 in the order inserted above.

INSERT INTO ticket_tags (ticket_id, tag_id) VALUES
  (1, 3),   -- autocomplete in global search - web
  (1, 8),
  (2, 1),   -- iOS login overlap
  (3, 2),   -- Android dark mode
  (4, 4),
  (4, 7),
  (4, 5),   -- Viking backend payments
  (5, 9),   -- onboarding analytics
  (6, 8),
  (6, 3),
  (7, 4),
  (7, 7),
  (8, 1),
  (9, 2),
  (10, 3),
  (10, 10),
  (11, 4),
  (12, 3),
  (12, 10),
  (13, 3),
  (14, 2),
  (15, 1),
  (16, 5),
  (16, 4),
  (17, 7),
  (17, 4),
  (18, 4),
  (19, 9),
  (19, 3),
  (20, 3),
  (21, 8),
  (21, 10),
  (22, 5),
  (23, 4),
  (24, 2),
  (25, 1),
  (26, 3),
  (27, 10),
  (28, 9),
  (29, 7),
  (29, 4),
  (30, 8),
  (31, 5),
  (31, 1),
  (32, 2),
  (33, 4),
  (34, 3),
  (35, 10),
  (36, 9),
  (37, 7),
  (38, 8),
  (39, 1),
  (40, 2),
  (41, 4),
  (42, 3),
  (43, 5),
  (44, 9),
  (45, 7),
  (46, 8),
  (47, 10),
  (48, 4),
  (49, 3),
  (50, 3),
  (50, 8);

COMMIT;


